include "exemples/math.ms";

var a = parse_number(input("Enter a: "));
var b = parse_number(input("Enter b: "));
print("a + b: " + (a + b));
print("a - b: " + (a - b));
print("a * b: " + (a * b));
print("a / b: " + (a / b));
print("a pow b: " + pow(a, b));
print("a & b: " + (a & b));
print("a | b: " + (a | b));
print("a ^ b: " + (a ^ b));
print("a % b: " + (a % b));
print("a << b: " + (a << b));
print("a >> b: " + (a >> b));
